import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './pro-admin.css';
import { ProAdmin } from './pro-admin';

const rides = [
  { id: 'RF-10842', customer: 'Aarav Sharma', service: 'Prime Sedan', driver: 'Rakesh Kumar', pickup: 'Sector 17, Chandigarh', drop: 'Airport Road, Mohali', fare: '₹342', status: 'In progress', time: '09:42 AM' },
  { id: 'RF-10841', customer: 'Simran Kaur', service: 'Auto', driver: 'Gurpreet Singh', pickup: 'Zirakpur Bus Stand', drop: 'Elante Mall', fare: '₹186', status: 'Completed', time: '09:22 AM' },
  { id: 'RF-10840', customer: 'Karan Mehta', service: 'Bike', driver: 'Aman Verma', pickup: 'Phase 7, Mohali', drop: 'Sector 35, Chandigarh', fare: '₹94', status: 'Driver arriving', time: '09:18 AM' },
  { id: 'RF-10839', customer: 'Neha Gupta', service: 'Outstation SUV', driver: '—', pickup: 'Chandigarh', drop: 'Manali', fare: '₹4,850', status: 'Searching', time: '09:08 AM' },
];
const nav = ['Overview','Live rides','Bookings','Customer onboarding','Drivers & KYC','Vendors & fleet','Vehicles','Service catalogue','Cities & geo fences','Fares & zones','Payments & payouts','Wallet & ledger','Commissions','Coupons & referrals','Notifications','Safety & SOS','Support','Reports','Audit logs','Roles & settings','Integrations & compliance'];
const icons = ['▦','◉','▤','♙','♧','▣','▱','◫','⌖','◇','₹','▤','%','◇','♧','!','?','↗','☷','⚙','⌁'];

function Stat({label, value, change, icon, tone}) { return <div className="stat"><div><p>{label}</p><h2>{value}</h2><span className={change?.startsWith('+') ? 'up':'muted'}>{change}</span></div><div className={'statIcon '+tone}>{icon}</div></div> }
function Status({children}) { return <span className={'status '+children.toLowerCase().replaceAll(' ','-')}>{children}</span> }

function App(){
 const [page,setPage]=useState('Overview'); const [panel,setPanel]=useState('Admin'); const [modal,setModal]=useState(false); const [notice,setNotice]=useState(''); const [query,setQuery]=useState('');
 const shown = useMemo(()=>rides.filter(r => Object.values(r).join(' ').toLowerCase().includes(query.toLowerCase())),[query]);
 const action=(m)=>{setNotice(m);setTimeout(()=>setNotice(''),2600)};
 return <div className="app">
  <aside><div className="brand"><div className="brandMark">R</div><div>Ride<span>Flow</span><small>Mobility platform</small></div></div>
  <div className="switcher"><button className={panel==='Admin'?'chosen':''} onClick={()=>setPanel('Admin')}>Admin</button><button className={panel==='Customer'?'chosen':''} onClick={()=>setPanel('Customer')}>Customer</button><button className={panel==='Driver'?'chosen':''} onClick={()=>setPanel('Driver')}>Driver</button></div>
  <nav>{nav.map((n,i)=><button key={n} className={page===n?'active':''} onClick={()=>setPage(n)}><i>{icons[i]}</i>{n}{n==='Support'&&<b>8</b>}</button>)}</nav>
  <div className="sideBottom"><div className="help">✦ <span><strong>Need help?</strong><br/>View knowledge base</span></div><div className="avatar">VK</div><div className="user"><strong>Vishal Kumar</strong><small>Super admin</small></div><span>⌄</span></div></aside>
  <main><header><div><p className="crumb">RideFlow / {panel}</p><h1>{page}</h1></div><div className="topActions"><button className="iconBtn">⌕</button><button className="iconBtn bell">♧<em>3</em></button><button className="primary" onClick={()=>setModal(true)}>+ New booking</button></div></header>
  {notice&&<div className="toast">✓ {notice}</div>}
  {panel==='Customer'?<CustomerDemo action={action}/>:panel==='Driver'?<DriverDemo action={action}/>:<ProAdmin page={page} action={action}/>} 
  </main>
  {modal&&<BookingModal close={()=>setModal(false)} action={action}/>} 
 </div>
}

function Admin({page,shown,query,setQuery,action}){if(page!=='Overview')return <AdminModule page={page} action={action}/>;
 return <><div className="hero"><div><span className="liveDot">● Live operations</span><h2>Good morning, Vishal 👋</h2><p>Here’s what’s happening across your mobility network today.</p></div><button onClick={()=>action('Report downloaded')} className="outline">⇩ Export report</button></div>
 <section className="stats"><Stat label="Total bookings" value="1,284" change="+12.5% vs last week" icon="▤" tone="blue"/><Stat label="Active rides" value="48" change="12 drivers arriving now" icon="⌖" tone="violet"/><Stat label="Today’s revenue" value="₹86,420" change="+8.2% vs yesterday" icon="₹" tone="green"/><Stat label="Online drivers" value="186" change="72% of approved drivers" icon="♙" tone="orange"/></section>
 <section className="grid"><div className="card revenue"><div className="cardTitle"><div><h3>Revenue performance</h3><p>Last 7 days</p></div><button className="select">This week⌄</button></div><div className="chart"><div className="ylabels"><span>₹100k</span><span>₹75k</span><span>₹50k</span><span>₹25k</span><span>₹0</span></div><div className="bars">{[52,68,44,79,62,90,74].map((v,i)=><div key={i}><i style={{height:v+'%'}}></i><span>{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'][i]}</span></div>)}</div></div></div>
 <div className="card service"><div className="cardTitle"><div><h3>Bookings by service</h3><p>Today</p></div><button className="dots">•••</button></div><div className="donut"><div><strong>1,284</strong><small>Bookings</small></div></div><div className="legend"><p><i className="l1"/>Cab <b>54%</b></p><p><i className="l2"/>Auto <b>26%</b></p><p><i className="l3"/>Bike <b>14%</b></p><p><i className="l4"/>Outstation <b>6%</b></p></div></div></section>
 <section className="card tableCard"><div className="cardTitle"><div><h3>Recent bookings</h3><p>Latest ride activity across all services</p></div><button className="textBtn" onClick={()=>action('Opening all bookings')}>View all →</button></div><div className="tableTools"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="⌕  Search booking, customer or driver"/><button className="filter">☷ Filter</button></div><table><thead><tr><th>BOOKING ID</th><th>CUSTOMER</th><th>SERVICE</th><th>DRIVER</th><th>ROUTE</th><th>FARE</th><th>STATUS</th><th></th></tr></thead><tbody>{shown.map(r=><tr key={r.id}><td><strong>{r.id}</strong><small>{r.time}</small></td><td>{r.customer}</td><td><span className="serviceTag">{r.service}</span></td><td>{r.driver}</td><td><span className="route">{r.pickup} <i>→</i> {r.drop}</span></td><td><strong>{r.fare}</strong></td><td><Status>{r.status}</Status></td><td><button className="more" onClick={()=>action('Booking '+r.id+' selected')}>•••</button></td></tr>)}</tbody></table></section></>}

const moduleData={
 'Bookings':{subtitle:'Search, monitor and manage every customer ride.',add:'New booking',columns:['Booking','Customer','Service','Driver','Fare','Status'],rows:[['RF-10842','Aarav Sharma','Prime Sedan','Rakesh Kumar','₹342','In progress'],['RF-10841','Simran Kaur','Auto','Gurpreet Singh','₹186','Completed'],['RF-10840','Karan Mehta','Bike','Aman Verma','₹94','Driver arriving']]},
 'Customers':{subtitle:'Manage rider profiles, wallet balances and ride activity.',add:'Add customer',columns:['Customer','Mobile','Total rides','Wallet','Last ride','Status'],rows:[['Aarav Sharma','98765 43210','24','₹120','Today, 9:42 AM','Active'],['Simran Kaur','99887 65432','18','₹420','Today, 9:22 AM','Active'],['Karan Mehta','98221 33445','6','₹0','08 Sep, 10:14 AM','Blocked']]},
 'Drivers':{subtitle:'Approve driver onboarding, KYC and availability.',add:'Add driver',columns:['Driver','Vehicle','Rating','Documents','Earnings','Status'],rows:[['Rakesh Kumar','Dzire · PB 65 AB 2183','4.9 ★','Verified','₹18,420','Online'],['Gurpreet Singh','Aura · PB 65 CF 8294','4.8 ★','Verified','₹16,815','On trip'],['Aman Verma','Activa · PB 65 EX 9091','4.7 ★','Licence pending','₹9,420','Offline']]},
 'Vendors & fleet':{subtitle:'Control fleet partners, commissions and settlement status.',add:'Add vendor',columns:['Fleet owner','Drivers','Vehicles','Today trips','Pending payout','Status'],rows:[['Maple Mobility Fleet','18','22','46','₹28,450','Approved'],['CityLink Cabs','12','15','31','₹14,820','Approved'],['NorthRide Partners','7','9','18','₹7,460','KYC review']]},
 'Vehicles':{subtitle:'Track vehicle eligibility, documents and driver assignment.',add:'Add vehicle',columns:['Vehicle','Category','Assigned driver','Documents','City','Status'],rows:[['PB 65 AB 2183','Prime Sedan','Rakesh Kumar','Verified','Chandigarh','Active'],['PB 65 CF 8294','Cab Mini','Gurpreet Singh','Verified','Mohali','Active'],['PB 65 EX 9091','Bike','Aman Verma','Insurance expires soon','Zirakpur','Review']]},
 'Coupons':{subtitle:'Create promotional offers and analyse redemptions.',add:'Create coupon',columns:['Code','Offer','Eligibility','Used','Expiry','Status'],rows:[['WELCOME50','₹50 off','First ride','482 / 1,000','30 Sep 2026','Active'],['AIRPORT20','20% off','Airport rides','134 / 500','20 Sep 2026','Active'],['FESTIVE100','₹100 off','All customers','0 / 2,000','31 Oct 2026','Scheduled']]},
 'Payments':{subtitle:'Review collections, wallet activity, refunds and settlements.',add:'Create payout',columns:['Reference','Type','User','Amount','Method','Status'],rows:[['PAY-88142','Ride payment','Aarav Sharma','₹342','UPI','Success'],['PYO-1472','Driver payout','Rakesh Kumar','₹5,480','Bank transfer','Pending'],['REF-1277','Ride refund','Karan Mehta','₹94','Wallet','Processed']]},
 'Safety & SOS':{subtitle:'Monitor SOS signals, disputes and trip safety escalation.',add:'Create safety case',columns:['Alert','Ride','Raised by','Location','Priority','Status'],rows:[['SOS-071','RF-10812','Customer','Sector 22, Chandigarh','High','Resolved'],['DIS-244','RF-10806','Driver','Mohali Airport','Medium','Open'],['SOS-067','RF-10790','Customer','Zirakpur','High','Resolved']]},
 'Support':{subtitle:'Resolve rider, driver and fleet support requests.',add:'New ticket',columns:['Ticket','Raised by','Subject','Priority','Assigned to','Status'],rows:[['SUP-2094','Aarav Sharma','Driver arrived late','Medium','Support team','Open'],['SUP-2090','Rakesh Kumar','Payout not received','High','Finance','In progress'],['SUP-2084','Maple Mobility','Vehicle document update','Low','KYC team','Resolved']]}
 ,'Reports':{subtitle:'Export business, ride, service and settlement performance reports.',add:'Build report',columns:['Report','Period','Generated by','Format','Last updated','Status'],rows:[['Revenue by city','September 2026','Vishal Kumar','CSV / PDF','Today, 9:20 AM','Ready'],['Driver payout summary','Week 37','Finance team','XLSX','Today, 8:00 AM','Ready'],['Cancellation analysis','September 2026','Operations','PDF','Yesterday','Scheduled']]}
 ,'Settings':{subtitle:'Control platform, business, notification and role configurations.',add:'Add admin role',columns:['Setting area','Configuration','Owner','Updated','Environment','Status'],rows:[['Business profile','RideFlow India','Super admin','Today','Production','Active'],['Payment gateway','Razorpay test ready','Finance','Yesterday','Sandbox','Active'],['Role permissions','6 custom roles','Super admin','08 Sep','Production','Active']]}
};
Object.assign(moduleData,{
 'Customer onboarding':{subtitle:'Review new rider accounts, OTP verification, consent and profile completion.',add:'Invite customer',columns:['Customer','Mobile','Verification','Profile','Consent','Status'],rows:[['Priya Malhotra','98144 20220','OTP verified','80% complete','Location pending','Pending'],['Rohan Bansal','98712 33004','OTP verified','Complete','Accepted','Active'],['Nisha Arora','99812 64118','OTP failed','—','—','Review']]},
 'Drivers & KYC':{subtitle:'Approve driver onboarding, identity checks, documents and activation.',add:'Add driver',columns:['Driver','Licence','Vehicle docs','Bank KYC','Application','Status'],rows:[['Rakesh Kumar','Verified','Verified','Verified','Approved','Online'],['Aman Verma','Pending','Verified','Verified','Under review','KYC review'],['Rajesh Saini','Verified','Expired RC','Pending','Action needed','Suspended']]},
 'Payments & payouts':{subtitle:'Review collections, wallet activity, refunds and settlement requests.',add:'Create payout',columns:['Reference','Type','User','Amount','Method','Status'],rows:[['PAY-88142','Ride payment','Aarav Sharma','₹342','UPI','Success'],['PYO-1472','Driver payout','Rakesh Kumar','₹5,480','Bank transfer','Pending'],['REF-1277','Ride refund','Karan Mehta','₹94','Wallet','Processed']]},
 'Commissions':{subtitle:'Set commission rules by city, service, driver or fleet partner.',add:'Create rule',columns:['Rule','Applies to','Service','Commission','Effective from','Status'],rows:[['Chandigarh standard','Independent drivers','Cab','18%','01 Sep 2026','Active'],['Maple fleet agreement','Maple Mobility Fleet','All services','12%','01 Sep 2026','Active'],['Bike launch incentive','Zirakpur drivers','Bike','10%','15 Sep 2026','Scheduled']]},
 'Notifications':{subtitle:'Create and schedule push, SMS and email communications.',add:'Create campaign',columns:['Campaign','Audience','Channel','Delivery','Scheduled','Status'],rows:[['Weekend airport offer','Chandigarh customers','Push + SMS','8,420 recipients','Sat, 9:00 AM','Scheduled'],['KYC document reminder','Drivers with expiry','Push + SMS','14 recipients','Today, 11:00 AM','Sent'],['Payout confirmation','Eligible drivers','Push','38 recipients','Today, 8:00 AM','Sent']]},
 'Roles & settings':{subtitle:'Control administrators, permissions, platform settings and integrations.',add:'Add admin role',columns:['Setting area','Configuration','Owner','Updated','Environment','Status'],rows:[['Business profile','RideFlow India','Super admin','Today','Production','Active'],['Payment gateway','Razorpay test ready','Finance','Yesterday','Sandbox','Active'],['Role permissions','6 custom roles','Super admin','08 Sep','Production','Active']]}
});
function PageHeader({title,subtitle,button,action}){return <div className="moduleHeadInline"><div><p className="crumb">Admin / Operations</p><h2>{title}</h2><p>{subtitle}</p></div><button className="primary" onClick={()=>action(button+' opened')}>+ {button}</button></div>}
function AdminModule({page,action}){if(page==='Live rides')return <LiveRides action={action}/>;if(page==='Fares & zones')return <FaresZones action={action}/>;const d=moduleData[page]||moduleData.Bookings;return <section className="adminModule"><PageHeader title={page} subtitle={d.subtitle} button={d.add} action={action}/><div className="moduleStats"><Stat label="Total" value={page==='Payments'?'₹2.84L':page==='Support'?'8':page==='Coupons'?'12':'1,284'} change="Updated today" icon="▦" tone="blue"/><Stat label="Active" value={page==='Drivers'?'186':page==='Customers'?'3,842':page==='Support'?'5':'48'} change="Live status" icon="◉" tone="green"/><Stat label="Needs action" value={page==='Drivers'?'14':page==='Payments'?'₹43k':'6'} change="Review required" icon="!" tone="orange"/></div><section className="card tableCard"><div className="cardTitle"><div><h3>{page} directory</h3><p>Demo data — filters and actions are ready for API connection.</p></div><button className="textBtn" onClick={()=>action('Export started')}>⇩ Export</button></div><div className="tableTools"><input placeholder={'⌕  Search '+page.toLowerCase()}/><button className="filter" onClick={()=>action('Filters opened')}>☷ Filter</button><button className="filter" onClick={()=>action('Date selector opened')}>⌄ This month</button></div><table><thead><tr>{d.columns.map(x=><th key={x}>{x.toUpperCase()}</th>)}<th>ACTION</th></tr></thead><tbody>{d.rows.map((r,i)=><tr key={i}>{r.map((c,j)=><td key={j}>{j===0?<strong>{c}</strong>:j===r.length-1?<Status>{c}</Status>:c}</td>)}<td><button className="textBtn" onClick={()=>action(r[0]+' details opened')}>View</button></td></tr>)}</tbody></table></section></section>}
function LiveRides({action}){return <section className="adminModule"><PageHeader title="Live rides" subtitle="Real-time trip dispatch, driver availability and safety monitoring." button="Manual booking" action={action}/><div className="liveLayout"><section className="liveMap"><div className="mapRoad lr1"/><div className="mapRoad lr2"/>{['🚕','🚗','🛺','🏍️','🚕'].map((x,i)=><span className={'vehicle v'+i} key={i}>{x}</span>)}<div className="mapLegend"><b>48 active rides</b><span>186 drivers online</span></div></section><section className="card dispatch"><h3>Dispatch queue <b>12</b></h3>{rides.slice(0,3).map(r=><div className="dispatchRide" key={r.id}><span className="roundIcon">⌖</span><div><strong>{r.id} · {r.service}</strong><small>{r.pickup} → {r.drop}</small></div><button onClick={()=>action('Driver assignment opened for '+r.id)}>Assign</button></div>)}<button className="outline wide" onClick={()=>action('All active trips opened')}>View all live rides</button></section></div><section className="card safety"><div><span className="sos">SOS</span><strong> Safety centre</strong><p>No unresolved emergency alerts right now.</p></div><button className="outline" onClick={()=>action('Safety alerts opened')}>Open alerts</button></section></section>}
function FaresZones({action}){return <section className="adminModule"><PageHeader title="Fares & zones" subtitle="Configure city coverage, service availability, fare cards and dynamic pricing." button="Add city zone" action={action}/><div className="zoneGrid"><section className="card zoneMap"><div className="zoneA">Chandigarh<br/><small>3 fare zones</small></div><div className="zoneB">Mohali<br/><small>2 fare zones</small></div><div className="zoneC">Zirakpur<br/><small>1 fare zone</small></div></section><section className="card fareCard"><h3>Prime Sedan · Chandigarh</h3><p>Local ride fare configuration</p><div className="fareRows"><span>Base fare <b>₹55</b></span><span>Per km <b>₹14</b></span><span>Per minute <b>₹2</b></span><span>Minimum fare <b>₹99</b></span></div><button className="primary wide" onClick={()=>action('Fare editor opened')}>Edit fare rules</button></section></div><div className="moduleStats"><Stat label="Cities live" value="3" change="Chandigarh, Mohali, Zirakpur" icon="⌖" tone="blue"/><Stat label="Service zones" value="6" change="All serviceable" icon="◇" tone="green"/><Stat label="Surge rules" value="4" change="Peak demand rules" icon="↗" tone="orange"/></div></section>}

function CustomerDemo({action}){const [service,setService]=useState('Cab');return <section className="mobileWrap"><div className="phone"><div className="phoneTop"><span>9:41</span><b>● ● ●</b></div><div className="customerHead"><div className="avatar">VK</div><div><small>Good morning</small><strong>Vishal 👋</strong></div><span>♧</span></div><div className="map"><div className="mapRoad r1"/><div className="mapRoad r2"/><div className="pin p1">●</div><div className="pin p2">⌖</div><span className="mapLabel">Your location</span></div><div className="rideSheet"><h2>Where are you going?</h2><button className="location" onClick={()=>action('Location search opened')}><i>●</i><span>Pickup location<small>Sector 17, Chandigarh</small></span><b>⌕</b></button><button className="location"><i className="red">●</i><span>Where to?<small>Search destination</small></span><b>›</b></button><h3>Choose your ride</h3><div className="serviceChoices">{['Cab','Auto','Bike','Rental'].map(x=><button className={service===x?'sel':''} key={x} onClick={()=>setService(x)}><strong>{x==='Cab'?'🚕':x==='Auto'?'🛺':x==='Bike'?'🏍️':'🚙'}</strong>{x}<small>{x==='Cab'?'₹124':x==='Auto'?'₹78':x==='Bike'?'₹62':'From ₹499'}</small></button>)}</div><button className="bookBtn" onClick={()=>action(service+' booking requested')}>Book {service}</button></div></div><div className="demoNote"><h2>Customer booking demo</h2><p>Tap a ride type and book it. This demonstrates the customer app flow using mock data.</p><div><span>✓ GPS pickup</span><span>✓ Fare estimate</span><span>✓ Coupons & wallet</span><span>✓ Live trip tracking</span></div></div></section>}
function DriverDemo({action}){const [online,setOnline]=useState(true);return <section className="mobileWrap"><div className="phone driverPhone"><div className="phoneTop"><span>9:41</span><b>● ● ●</b></div><div className="driverHead"><div><small>Wednesday, 11 September</small><h2>Hello, Rakesh</h2></div><button onClick={()=>setOnline(!online)} className={online?'online':'offline'}><i/> {online?'Online':'Offline'}</button></div><div className="driverMap"><div className="vehicle">🚕</div><p>You're in a high-demand area</p></div><div className="earn"><span>Today’s earnings<strong>₹1,860</strong></span><span>Trips<strong>08</strong></span><span>Rating<strong>4.9 ★</strong></span></div><div className="request"><div className="requestTop"><span>New ride request</span><b>00:18</b></div><h3>Sector 17 → Mohali Airport</h3><p>3.8 km pickup · 14.2 km trip</p><div className="fareRow"><strong>₹342</strong><span>Estimated earning</span><b>Prime Sedan</b></div><div className="requestBtns"><button onClick={()=>action('Ride request declined')}>Decline</button><button onClick={()=>action('Ride accepted — navigation started')}>Accept ride</button></div></div></div><div className="demoNote"><h2>Driver partner demo</h2><p>Driver can switch availability, accept requests, start trip with OTP, view earnings and request payouts.</p></div></section>}
function BookingModal({close,action}){const [step,setStep]=useState(1); return <div className="modalBack"><div className="modal"><button className="close" onClick={close}>×</button><span className="step">NEW BOOKING · STEP {step} OF 2</span><h2>{step===1?'Create a ride booking':'Confirm booking details'}</h2>{step===1?<><label>Customer mobile number<input defaultValue="98765 43210"/></label><label>Pickup location<input defaultValue="Sector 17, Chandigarh"/></label><label>Destination<input placeholder="Enter drop location"/></label><div className="modalActions"><button onClick={close}>Cancel</button><button className="primary" onClick={()=>setStep(2)}>Continue</button></div></>:<><div className="confirm"><p><span>Service</span><b>Prime Sedan</b></p><p><span>Estimated fare</span><b>₹342</b></p><p><span>Payment</span><b>Cash</b></p></div><div className="modalActions"><button onClick={()=>setStep(1)}>Back</button><button className="primary" onClick={()=>{close();action('Booking RF-10843 created successfully')}}>Confirm booking</button></div></>}</div></div>}
createRoot(document.getElementById('root')).render(<App/>);
