import React, {useState} from 'react';
import Select from 'react-select';
import Swal from 'sweetalert2';

const rows={
 'Bookings':[['RF-10842','Aarav Sharma','Prime Sedan','Rakesh Kumar','₹342','In progress'],['RF-10841','Simran Kaur','Auto','Gurpreet Singh','₹186','Completed'],['RF-10840','Karan Mehta','Bike','Aman Verma','₹94','Driver arriving']],
 'Customer onboarding':[['Priya Malhotra','98144 20220','OTP verified','80%','Pending'],['Rohan Bansal','98712 33004','OTP verified','100%','Active']],
 'Drivers & KYC':[['Rakesh Kumar','DL verified','RC + insurance verified','Bank verified','Approved'],['Aman Verma','DL pending','RC verified','Bank verified','Under review'],['Rajesh Saini','DL verified','RC expired','Bank pending','Action needed']],
 'Vendors & fleet':[['Maple Mobility Fleet','18','22','₹28,450','Approved'],['CityLink Cabs','12','15','₹14,820','Approved']],
 'Vehicles':[['PB 65 AB 2183','Prime Sedan','Rakesh Kumar','Verified','Active'],['PB 65 EX 9091','Bike','Aman Verma','Insurance expiring','Review']],
 'Payments & payouts':[['PAY-88142','Ride payment','Aarav Sharma','₹342','UPI','Success'],['PYO-1472','Driver payout','Rakesh Kumar','₹5,480','Bank','Pending'],['REF-1277','Refund','Karan Mehta','₹94','Wallet','Processed']],
 'Commissions':[['Chandigarh standard','Independent drivers','Cab','18%','Active'],['Maple fleet agreement','Maple Fleet','All','12%','Active'],['Bike launch incentive','Zirakpur drivers','Bike','10%','Scheduled']],
 'Coupons':[['WELCOME50','₹50 off','First ride','482 / 1000','Active'],['AIRPORT20','20% off','Airport','134 / 500','Active']],
 'Notifications':[['Weekend airport offer','8,420 customers','Push + SMS','Sat, 9 AM','Scheduled'],['KYC reminder','14 drivers','Push + SMS','Today, 11 AM','Sent']],
 'Safety & SOS':[['SOS-071','RF-10812','Customer','Sector 22','High','Resolved'],['DIS-244','RF-10806','Driver','Mohali Airport','Medium','Open']],
 'Support':[['SUP-2094','Aarav Sharma','Driver arrived late','Medium','Open'],['SUP-2090','Rakesh Kumar','Payout not received','High','In progress']],
 'Reports':[['Revenue by city','September 2026','CSV / PDF','Today','Ready'],['Driver payout summary','Week 37','XLSX','Today','Ready']],
 'Roles & settings':[['Super Admin','All permissions','Vishal Kumar','Active'],['Operations Manager','Rides, drivers, SOS','2 members','Active'],['Finance Executive','Payments, payouts','1 member','Active']],
 'Service catalogue':[['Prime Sedan','Cab','4 seats','Enabled'],['Auto','Auto','3 seats','Enabled'],['Bike','Bike','1 rider','Enabled'],['Outstation SUV','Outstation','6 seats','Enabled']],
 'Cities & geo fences':[['Chandigarh','3 service zones','Airport zone','Active'],['Mohali','2 service zones','Railway station','Active'],['Zirakpur','1 service zone','No restricted zone','Active']],
 'Wallet & ledger':[['WLT-8121','Customer credit','Aarav Sharma','+ ₹120','Completed'],['WLT-8119','Driver deduction','Rakesh Kumar','− ₹42','Completed'],['WLT-8117','Referral reward','Simran Kaur','+ ₹75','Pending']],
 'Coupons & referrals':[['WELCOME50','Coupon','First ride','482 uses','Active'],['REF-VISHAL','Customer referral','₹75 credit','28 conversions','Active'],['DRV-RAKESH','Driver referral','₹500 reward','4 conversions','Active']],
 'Audit logs':[['AUD-8042','Vishal Kumar','Approved driver KYC','Rakesh Kumar','Today, 09:42'],['AUD-8038','Finance Team','Released payout','PYO-1472','Today, 08:14'],['AUD-8030','Operations','Updated fare rule','Chandigarh sedan','Yesterday']],
 'Integrations & compliance':[['Google Maps','Maps / routes / places','Connected','Active'],['Razorpay','Payments & refunds','Sandbox','Active'],['SMS / WhatsApp','OTP & notifications','Configure keys','Review'],['GST & tax','Invoice settings','18% GST','Active']],
};
const cols={
 'Bookings':['Booking','Customer','Service','Driver','Fare','Status'],
 'Customer onboarding':['Customer','Mobile','Verification','Profile','Status'],'Drivers & KYC':['Driver','Driving licence','Vehicle documents','Bank KYC','Application'], 'Vendors & fleet':['Fleet','Drivers','Vehicles','Payout','Status'],'Vehicles':['Vehicle','Category','Driver','Documents','Status'],'Payments & payouts':['Reference','Type','User','Amount','Method','Status'],'Commissions':['Rule','Applies to','Service','Commission','Status'],'Coupons':['Coupon','Offer','Eligibility','Usage','Status'],'Notifications':['Campaign','Audience','Channel','Schedule','Status'],'Safety & SOS':['Alert','Ride','Raised by','Location','Priority','Status'],'Support':['Ticket','Raised by','Subject','Priority','Status'],'Reports':['Report','Period','Format','Updated','Status'],'Roles & settings':['Role','Permissions','Members','Status'],'Service catalogue':['Service','Type','Capacity','Status'],'Cities & geo fences':['City','Coverage','Special zone','Status'],'Wallet & ledger':['Reference','Type','Account','Amount','Status'],'Coupons & referrals':['Code','Type','Reward','Performance','Status'],'Audit logs':['Log ID','Actor','Action','Target','Timestamp'],'Integrations & compliance':['Service','Use','Configuration','Status']
};
const labels={
 'Customer onboarding':['Invite customer','Review onboarding queue'],'Drivers & KYC':['Add driver','Approve KYC and documents'],'Vendors & fleet':['Add vendor','Manage fleet contracts and KYC'],'Vehicles':['Add vehicle','Manage vehicle compliance'],'Payments & payouts':['Create payout','Approve refunds and settlements'],'Commissions':['Create rule','Set commission and incentive rules'],'Coupons':['Create coupon','Promotions and referral discounts'],'Notifications':['Create campaign','Push, SMS and email delivery'],'Safety & SOS':['Open safety case','Live safety incidents and disputes'],'Support':['Create ticket','Support conversations and escalation'],'Reports':['Build report','Performance and finance exports'],'Roles & settings':['Add admin role','Role, permissions and integrations'],'Service catalogue':['Add service','Manage cab, auto, bike, rental and outstation categories'],'Cities & geo fences':['Add city','Set serviceable polygons, airport and restricted zones'],'Wallet & ledger':['Adjust wallet','Review credits, debits and referral rewards'],'Coupons & referrals':['Create promotion','Manage customer and driver referrals'],'Audit logs':['Export audit log','Track every sensitive admin action'],'Integrations & compliance':['Configure integration','Maps, payments, OTP, WhatsApp, GST and policy controls']
};
const selectStyle={control:(b)=>({...b,minHeight:40,borderColor:'#dfe5ec',borderRadius:8,boxShadow:'none'}),menu:(b)=>({...b,zIndex:30})};
const ask=async(title,text='This demo action will be connected to the Laravel API later.')=>{const a=await Swal.fire({title,text,icon:'question',showCancelButton:true,confirmButtonColor:'#218d63',confirmButtonText:'Continue'});if(a.isConfirmed)Swal.fire({title:'Saved in demo',text:'The UI workflow has been confirmed.',icon:'success',confirmButtonColor:'#218d63'});};
function Badge({children}){return <span className={'pBadge '+String(children).toLowerCase().replaceAll(' ','-')}>{children}</span>}
function ModuleHeader({title,subtitle,button}){return <div className="pHeader"><div><p>Admin / {title}</p><h2>{title}</h2><span>{subtitle}</span></div><button className="primary" onClick={()=>ask(button)}>{button}</button></div>}
function Mini({label,value,note,icon}){return <div className="pMini"><span className="pMiniIcon">{icon}</span><p>{label}<b>{value}</b><small>{note}</small></p></div>}
function DetailExtras({page}){if(page==='Bookings')return <><section className="bookingRoute"><h3>Live route & tracking</h3><div><span className="carTrack">🚕</span><b>Driver GPS online · 4 min away</b><small>ETA 09:56 AM · Geofence: Pickup zone entered</small></div><button onClick={()=>ask('Open route playback')}>Route playback</button></section><section className="fareBreak"><h3>Fare breakup</h3><p>Base fare <b>₹55</b></p><p>Distance 14.2 km <b>₹198</b></p><p>Time charge <b>₹48</b></p><p>Tax <b>₹41</b></p><p>Total <b>₹342</b></p></section><div className="drawerActions"><button onClick={()=>ask('Cancel booking','Cancellation fee and refund options will be shown.')}>Cancel / refund</button><button className="primary" onClick={()=>ask('Reassign driver')}>Assign / reassign driver</button></div></>;
 if(['Customer onboarding','Drivers & KYC','Vendors & fleet','Vehicles'].includes(page))return <section className="profileTabs"><h3>Profile activity</h3><div><b>Trips</b><b>Wallet</b><b>Documents</b><b>Support</b></div><p>Recent activity, payouts, saved locations, uploaded documents and support cases are available in these profile tabs.</p><button onClick={()=>ask('Open full profile')}>Open full profile</button></section>;
 if(page==='Payments & payouts')return <section className="ledger"><h3>Wallet ledger & invoice</h3><p>Ride collection <b>+ ₹342</b></p><p>Platform commission <b>− ₹61.56</b></p><p>Driver payable <b>₹280.44</b></p><button onClick={()=>ask('Generate GST invoice')}>GST invoice PDF</button><button onClick={()=>ask('Open settlement statement')}>Settlement statement</button></section>;
 if(page==='Safety & SOS')return <section className="sosDetail"><h3>Emergency contacts & closure</h3><p><b>Customer:</b> Aarav Sharma · +91 98765 43210 <button onClick={()=>ask('Call customer')}>Call</button></p><p><b>Driver:</b> Rakesh Kumar · +91 98111 33221 <button onClick={()=>ask('Call driver')}>Call</button></p><textarea placeholder="Incident notes and closure report"/><button className="primary" onClick={()=>ask('Close safety incident')}>Close incident</button></section>;
 if(page==='Support')return <section className="ticketChat"><h3>Support conversation · SLA 01:42:18</h3><p className="userMsg">Customer: Driver arrived late and I missed my flight.</p><p className="adminMsg">Support: We are reviewing the trip timeline.</p><input placeholder="Write internal note or reply"/><button onClick={()=>ask('Attach file')}>Attach</button><button className="primary" onClick={()=>ask('Send reply')}>Send reply</button></section>;
 return null}
function DetailDrawer({page,row,close}){const fields=cols[page]||[];return <div className="drawerBack" onMouseDown={close}><aside className="detailDrawer" onMouseDown={e=>e.stopPropagation()}><button className="drawerClose" onClick={close}>×</button><span className="drawerType">{page}</span><h2>{row[0]}</h2><Badge>{row[row.length-1]}</Badge><div className="drawerTabs"><b>Overview</b><span>Timeline</span><span>Notes</span><span>Audit</span></div><section>{fields.map((x,i)=><p key={x}><span>{x}</span><strong>{row[i]||'—'}</strong></p>)}</section><DetailExtras page={page}/><section className="detailTimeline"><h3>Activity timeline & audit log</h3><p><i/>Created by Operations Team · Today, 9:14 AM</p><p><i/>Updated by Vishal Kumar · Today, 9:42 AM</p><p><i/>Notification event logged successfully.</p></section><div className="drawerActions"><button onClick={()=>ask('Request change')}>Request change</button><button className="primary" onClick={()=>ask('Save record changes')}>Save changes</button></div></aside></div>}
function DataTable({page}){const [search,setSearch]=useState('');const [detail,setDetail]=useState(null);const data=(rows[page]||[]).filter(r=>r.join(' ').toLowerCase().includes(search.toLowerCase()));return <><section className="pPanel"><div className="pTableTop"><div><h3>{page} directory</h3><p>Manage records and open individual details.</p></div><div className="bulk"><button onClick={()=>ask('Bulk actions','Approve, block, notify or export selected records.')}>Bulk actions</button><button className="textBtn" onClick={()=>ask('Export '+page)}>⇩ Export</button></div></div><div className="pFilters"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={'Search '+page.toLowerCase()}/><Select styles={selectStyle} defaultValue={{label:'All statuses',value:'all'}} options={[{label:'All statuses',value:'all'},{label:'Active',value:'active'},{label:'Pending review',value:'pending'}]}/><button className="filter" onClick={()=>ask('Advanced filters')}>☷ Filters</button></div><div className="pTableWrap"><table><thead><tr><th><input type="checkbox"/></th>{(cols[page]||[]).map(x=><th key={x}>{x}</th>)}<th>Action</th></tr></thead><tbody>{data.map((r,i)=><tr key={i}><td><input type="checkbox"/></td>{r.map((x,j)=><td key={j}>{j===0?<strong>{x}</strong>:j===r.length-1?<Badge>{x}</Badge>:x}</td>)}<td><button className="pView" onClick={()=>setDetail(r)}>View →</button></td></tr>)}</tbody></table></div></section>{detail&&<DetailDrawer page={page} row={detail} close={()=>setDetail(null)}/>}</>}
function Workflow({title,items}){return <section className="pPanel pWorkflow"><h3>{title}</h3><div>{items.map((x,i)=><React.Fragment key={x}><span className="stepDot">{i+1}</span><p><b>{x}</b><small>{i===items.length-1?'Complete and notify the user':'Required review step'}</small></p>{i<items.length-1&&<i/>}</React.Fragment>)}</div></section>}
function KycPage({page}){return <><ModuleHeader title={page} subtitle={labels[page][1]} button={labels[page][0]}/><div className="pCards"><Mini label="Awaiting review" value="14" note="8 driver applications" icon="✓"/><Mini label="Document expiring" value="6" note="Next 30 days" icon="!"/><Mini label="Approval time" value="18 min" note="Average today" icon="◷"/></div><div className="pSplit"><Workflow title="Driver approval workflow" items={['Mobile OTP & profile','Driving licence validation','RC, insurance & PUC','Bank / PAN verification','Admin approval and activation']}/><section className="pPanel pReview"><h3>Document review — Aman Verma</h3><p>Application submitted 12 minutes ago</p><div className="docRow"><span>Driving licence</span><Badge>Pending</Badge><button onClick={()=>ask('Review driving licence')}>Preview</button></div><div className="docRow"><span>Vehicle RC</span><Badge>Verified</Badge><button onClick={()=>ask('Review RC document')}>Preview</button></div><div className="docActions"><button onClick={()=>ask('Reject application','A rejection reason form will appear.')}>Reject</button><button className="primary" onClick={()=>ask('Approve driver','This will activate the driver account.')}>Approve & activate</button></div></section></div><DataTable page={page}/></>}
function Live(){return <><ModuleHeader title="Live rides" subtitle="Real-time trip dispatch, location tracking and safety monitoring." button="+ Manual booking"/><div className="pSplit live"><section className="pTrackMap"><span className="mapPin one">🚕</span><span className="mapPin two">🛺</span><span className="mapPin three">🏍️</span><div><b>48 active trips</b><small>186 drivers online</small></div></section><section className="pPanel pQueue"><h3>Dispatch queue <Badge>12</Badge></h3>{['RF-10842 · Prime Sedan','RF-10840 · Bike','RF-10839 · Outstation SUV'].map((x,i)=><div key={x}><span>⌖</span><p><b>{x}</b><small>{i===0?'Sector 17 → Mohali Airport':'Waiting for driver assignment'}</small></p><button onClick={()=>ask('Assign driver')}>Assign</button></div>)}<button className="outline pFull" onClick={()=>ask('Open all live trips')}>View all active trips</button></section></div><section className="pAlert"><span>SOS</span><div><b>Safety command centre</b><p>No unresolved SOS alert. Escalation rules are enabled for active trips.</p></div><button onClick={()=>ask('Open SOS console')}>Open console</button></section></>}
function Fare(){return <><ModuleHeader title="Fares & zones" subtitle="Configure city coverage, fare cards, rental/outstation rules and surge pricing." button="+ Add city zone"/><div className="pSplit"><section className="pZone"><b>Chandigarh</b><i>3 fare zones</i><b>Mohali</b><i>2 fare zones</i><b>Zirakpur</b><i>1 fare zone</i></section><section className="pPanel pRule"><h3>Prime Sedan · Chandigarh</h3><p>Local fare card</p>{[['Base fare','₹55'],['Per km','₹14'],['Per minute','₹2'],['Minimum fare','₹99'],['Night surcharge','20%']].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}<button className="primary pFull" onClick={()=>ask('Edit fare rules')}>Edit fare and surge rules</button></section></div><div className="pCards"><Mini label="Cities live" value="3" note="All serviceable" icon="⌖"/><Mini label="Service zones" value="6" note="Map polygon zones" icon="◇"/><Mini label="Surge rules" value="4" note="Demand based" icon="↗"/></div></>}
function Reports(){return <><ModuleHeader title="Reports" subtitle="Build decision-ready reports with filtering and export controls." button="+ Build report"/><div className="pReport"><div><h3>Revenue overview</h3><b>₹8,64,200</b><span>+12.5% versus previous period</span><div className="pBars">{[44,62,51,83,69,92,74].map(x=><i style={{height:x+'%'}} key={x}/>)}</div><small>Mon &nbsp; Tue &nbsp; Wed &nbsp; Thu &nbsp; Fri &nbsp; Sat &nbsp; Sun</small></div><div><h3>Generate report</h3><label>Report type<Select styles={selectStyle} defaultValue={{label:'Revenue by city',value:'city'}} options={[{label:'Revenue by city',value:'city'},{label:'Driver earnings',value:'drivers'},{label:'Cancellations',value:'cancel'}]}/></label><label>Format<Select styles={selectStyle} defaultValue={{label:'PDF',value:'pdf'}} options={[{label:'PDF',value:'pdf'},{label:'CSV',value:'csv'},{label:'XLSX',value:'xlsx'}]}/></label><button className="primary pFull" onClick={()=>ask('Generate report','A secure report generation job will be queued.')}>Generate export</button></div></div><DataTable page="Reports"/></>}
function ControlPanel({page}){if(!['Payments & payouts','Commissions','Notifications','Safety & SOS','Support','Roles & settings'].includes(page))return null;const content={
 'Payments & payouts':['Payout & refund review',['Payout reference','PYO-1472'],['Net amount','₹5,480'],['Refund approval','Request supporting note']],
 'Commissions':['Commission rule builder',['Rule name','Chandigarh standard'],['Commission type','Percentage'],['Value','18%']],
 'Notifications':['Campaign composer',['Campaign name','Weekend airport offer'],['Audience','Chandigarh customers'],['Message','Save 20% on your airport ride this weekend.']],
 'Safety & SOS':['Incident command centre',['Incident ID','SOS-071'],['Emergency contact','Call primary contact'],['Resolution notes','Record incident outcome']],
 'Support':['Ticket response & SLA',['Ticket','SUP-2094'],['Assign to','Support Team'],['Internal note','Visible to team only']],
 'Roles & settings':['Admin access & integration',['Role name','Operations Manager'],['Permission set','Rides, drivers, safety'],['Audit log','All sensitive changes enabled']]
 }[page];return <section className="pPanel controlPanel"><div><h3>{content[0]}</h3><p>Use this interface before API connection for the complete approval workflow.</p></div><div className="controlFields">{content.slice(1).map(x=><label key={x[0]}>{x[0]}<input defaultValue={x[1]}/></label>)}</div><div className="controlActions"><button onClick={()=>ask('Save as draft')}>Save draft</button><button className="primary" onClick={()=>ask('Submit '+page+' workflow')}>Submit for approval</button></div></section>}
function Standard({page}){if(page==='Drivers & KYC'||page==='Customer onboarding')return <KycPage page={page}/>;if(page==='Live rides')return <Live/>;if(page==='Fares & zones')return <Fare/>;if(page==='Reports')return <Reports/>;const [button,subtitle]=labels[page]||['+ New item','Manage this area'];return <><ModuleHeader title={page} subtitle={subtitle} button={button}/><div className="pCards"><Mini label="Total records" value={page==='Payments & payouts'?'₹2.84L':page==='Notifications'?'11':'48'} note="Updated today" icon="▦"/><Mini label="Active" value={page==='Safety & SOS'?'0 alerts':'36'} note="Current status" icon="◉"/><Mini label="Needs action" value={page==='Commissions'?'3 rules':'6'} note="Review required" icon="!"/></div>{page==='Notifications'&&<Workflow title="Campaign flow" items={['Select audience segment','Choose Push, SMS or Email','Review scheduled delivery','View delivery and click metrics']}/>} {page==='Payments & payouts'&&<Workflow title="Payout protection flow" items={['Validate earning ledger','Verify bank account','Finance approval','Release and notify recipient']}/>} {page==='Safety & SOS'&&<Workflow title="Emergency response flow" items={['SOS received','Call rider and driver','Track trip and contact emergency number','Create incident outcome']}/>}<ControlPanel page={page}/><DataTable page={page}/></>}
export function ProAdmin({page}){return <main className="proAdmin">{page==='Overview'?<Overview/>:<Standard page={page}/>}</main>}
function Overview(){return <><ModuleHeader title="Overview" subtitle="Monitor operations, financial health and urgent actions." button="+ Manual booking"/><div className="pCards"><Mini label="Total bookings" value="1,284" note="+12.5% this week" icon="▤"/><Mini label="Active rides" value="48" note="12 drivers arriving" icon="⌖"/><Mini label="Today’s revenue" value="₹86,420" note="+8.2% yesterday" icon="₹"/><Mini label="Online drivers" value="186" note="72% approved drivers" icon="♙"/></div><div className="pAlert"><span>!</span><div><b>6 admin actions require attention</b><p>3 driver documents, 2 payout requests and 1 high-priority ticket are waiting.</p></div><button onClick={()=>ask('Open action centre')}>Review</button></div><Reports/></>}
